[tool.poetry]
name = "globalise-tools"
version = "0.1.1"
description = ""
authors = ["Bram Buitendijk <bram.buitendijk@di.huc.knaw.nl>"]
readme = "README.md"
packages = [{ include = "globalise_tools" }]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"

annorepo-client = "^0.1.3"

textrepo-client = "^0.5.2"

pagexml-tools = "^0.5.0"

blessedtable = "^1.0.0"
colorama = "^0.4.6"
dataclasses-json = "^0.5.13"
dkpro-cassis = "^0.9.1"
icecream = "^2.1.3"
jsondataclass = "^0.3.0"
loguru = "^0.7.0"
pycaprio = "^0.2.1"
spacy = { version = "^3.4.3" }
stam = "^0.5.0"
tabulate = "^0.9.0"
uuid = "^1.30"
uri = { git = "https://github.com/marrow/uri.git", rev = "5b58db87451ca4680004a8993a56bfc4dafff4d4" }
xlsxwriter = "^3.0.3"
hydra-core = "^1.3.2"
appengine-python-standard = "^1.1.3"
progressbar2 = "^4.2.0"
xmldict = "^0.4.1"
intervaltree = "^3.1.0"

[tool.poetry.dev-bram.dependencies]
textrepo-client = { path = "/Users/bram/workspaces/textrepo/textrepo-client-python", develop = true }
annorepo-client = { path = "/Users/bram/workspaces/annorepo/annorepo-client", develop = true }
provenance-client = { path = "/Users/bram/workspaces/provenance/provenance-python-client", develop = true }
pagexml-tools = { path = "/Users/bram/workspaces/pagexml", develop = true }
spacy = { extras = ["apple"], version = "^3.4.3" }


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
