[[analiticcl]]
id = "nl_voc_analiticcl"
name = "NL VOC groundtruth lexicon"
alphabet = "simple.alphabet.tsv"

[[analiticcl.lexicons]]
filename = "../langdetect/lexicons/nl_voc.tsv"

[[fst]]
id = "nl_voc_fst"
name = "NL VOC groundtruth lexicon"
file = "../langdetect/lexicons/nl_voc.tsv"
distance = 2

[[analiticcl]]
id = "extracted_analiticcl"
name = "Extracted Globalise lexicon (all t>1)"
alphabet = "simple.alphabet.tsv"

[[analiticcl.lexicons]]
filename = "all.freqs"

[[fst]]
id = "extracted_fst"
name = "Extracted Globalise lexicon (all t>1)"
alphabet = "simple.alphabet.tsv"
file = "extracted.freqs"
distance = 2

[[lookup]]
id = "inthislex"
name = "INT Historisch Lexicon"
file = "int_historisch_lexicon_variants.tsv"

[[lookup]]
id = "odwn"
name = "Open Dutch Wordnet"
file = "odwn.tsv"

