[[analiticcl]]
id = "nl_voc_analiticcl"
name = "NL VOC groundtruth lexicon"
alphabet = "simple.alphabet.tsv"

[[analiticcl.lexicons]]
filename = "../langdetect/lexicons/nl_voc.tsv"

[[fst]]
id = "nl_voc_fst"
name = "NL VOC groundtruth lexicon"
file = "../langdetect/lexicons/nl_voc.tsv"
distance = 2
