server {
    server_name localhost;
    listen 8080;
    #http2 on;

    location /entities/all {
        proxy_pass http://localhost:7019/;
    }

    location /entities/1119 {
        proxy_pass http://localhost:11119/;
    }

    location /entities/3598 {
        proxy_pass http://localhost:13598/;
    }

    location / {
        proxy_pass http://localhost:7019/;
    }
}
