import os
import sys
from pathlib import Path
from typing import Any

import multiprocess as mp
import orjson
from loguru import logger

import globalise_tools.pagexml_tools as pt
import globalise_tools.url_factory as uf
import scripts.gt_ner_xmi_to_wa as nx
from globalise_tools.creator import CreatorFactory
from globalise_tools.logger_tools import log_reading_file
from globalise_tools.model import Dimensions
from scripts.gt_ner_xmi_to_wa import XMIProcessorFactory


class AnnotationPageFactory:
    def __init__(
            self,
            inventory_number: str,
            pagexml_dir: str,
            xmi_dir: str,
            xmi_processor_factory: nx.XMIProcessorFactory,
            manifest_path: str,
            script_path: str
    ) -> None:
        self.errors = []
        self.inventory_number = inventory_number
        self.pagexml_dir = pagexml_dir
        self.xmi_dir = xmi_dir
        self.entity_pages = {}
        self.event_pages = {}
        self.transcription_pages = {}
        self.xmi_processor_factory = xmi_processor_factory
        self.script_path = script_path
        self._load_manifest(manifest_path)

    def build_annotation_pages(self) -> None:
        if not self.errors:
            pagexml_paths = sorted(Path(self.pagexml_dir).glob("*.xml"))
            # self._run_in_parallel(pagexml_paths)
            self._run_sequentially(pagexml_paths)

    def _run_in_parallel(self, pagexml_paths: list[Path], pool_size: int = 5):
        with mp.Pool(pool_size) as p:
            results = p.map(func=self._process_pagexml, iterable=pagexml_paths)
        for page_id, transcription_annotation_page, entity_annotation_page, event_annotation_page in results:
            self.transcription_pages[page_id] = transcription_annotation_page
            if entity_annotation_page:
                self.entity_pages[page_id] = entity_annotation_page
            if event_annotation_page:
                self.event_pages[page_id] = event_annotation_page

    def _run_sequentially(self, pagexml_paths: list[Path]):
        for pagexml_path in pagexml_paths:
            page_id, transcription_annotation_page, entity_annotation_page, event_annotation_page = self._process_pagexml(
                pagexml_path)
            self.transcription_pages[page_id] = transcription_annotation_page
            if entity_annotation_page:
                self.entity_pages[page_id] = entity_annotation_page
            if event_annotation_page:
                self.event_pages[page_id] = event_annotation_page

    def _process_pagexml(
            self,
            pagexml_path: Path
    ):
        page_id = pagexml_path.name.split("/")[-1].replace(".xml", "")
        xmi_path = Path(f"{self.xmi_dir}/{page_id}.xmi")
        dp = DocumentPageProcessor(
            page_id=page_id,
            pagexml_path=pagexml_path,
            xmi_path=xmi_path,
            xpf=self.xmi_processor_factory,
            iiif_base_uri_idx=self.iiif_base_uri_idx,
            canvas_id_idx=self.canvas_id_idx,
            script_path=self.script_path,
            manifest_item_idx=self.manifest_item_idx,
            manifest=self.manifest
        )
        return page_id, dp.transcription_annotation_page, dp.entity_annotation_page, dp.event_annotation_page

    def _load_manifest(self, manifest_path: str) -> None:
        if os.path.exists(manifest_path):
            log_reading_file(manifest_path)
            with open(manifest_path) as f:
                manifest = orjson.loads(f.read())
            self.manifest_item_idx, self.iiif_base_uri_idx, self.canvas_id_idx = nx.index_manifest_items(manifest)
            self.manifest = manifest
        else:
            self.errors.append(f"No manifest found at {manifest_path}")


class DocumentPageProcessor:

    def __init__(
            self,
            page_id: str,
            pagexml_path: Path,
            xmi_path: Path,
            xpf: XMIProcessorFactory,
            iiif_base_uri_idx,
            canvas_id_idx,
            script_path: str,
            manifest_item_idx,
            manifest
    ):
        self.page_id = page_id
        self.pagexml_path = pagexml_path
        self.xmi_path = xmi_path
        xml_string = self._read_page_xml(pagexml_path)
        self.transcription_annotation_page = {}
        self.entity_annotation_page = None
        self.event_annotation_page = None
        creator = CreatorFactory(script_paths=[script_path], commit_id=xpf.commit_id) \
            .creator(
            label="Creation of Web Annotations from NER output in XMI format (generated by the GLOBALISE NER model).")

        normalized_page_text = ""
        canvas_id = uf.canvas_url(page_id)
        annotation_page_builder = pt.TranscriptionAnnotationPageBuilder(
            page_id=page_id,
            xml_string=xml_string,
            canvas_id=canvas_id,
            script_path=script_path,
            commit_id=xpf.commit_id
        )
        if xmi_path.exists():
            htr_word_offsets = annotation_page_builder.htr_word_offsets
            log_reading_file(xmi_path)
            plain_text_source = nx.handle_page_xml(
                xmi_path=str(xmi_path),
                page_xml_path=str(pagexml_path),
                xpf=xpf,
                iiif_base_uri_for_base_name=iiif_base_uri_idx,
                canvas_id_for_base_name=canvas_id_idx,
            )

            ner_annotations, event_annotations, normalized_page_text, normalized_word_offsets = nx.handle_xmi(
                xmi_path=str(xmi_path),
                ner_annotations=[],
                event_annotations=[],
                xpf=xpf,
                plain_text_source=plain_text_source,
                manifest=manifest,
                manifest_item_idx=manifest_item_idx,
                htr_offset=htr_word_offsets,
                presentation_version=3
            )

            canvas_dimensions = {self._page_id(c): Dimensions(c["width"], c["height"]) for c in
                                 manifest["items"]}
            if ner_annotations:
                self.entity_annotation_page = self._make_annotation_page(
                    page_id=page_id,
                    annotations=ner_annotations,
                    canvas_dimensions=canvas_dimensions,
                    creator=creator,
                    anno_type="Entities",
                    page_type=uf.AnnotationPageType.ENTITIES
                )
            if event_annotations:
                self.event_annotation_page = self._make_annotation_page(
                    page_id=page_id,
                    annotations=event_annotations,
                    canvas_dimensions=canvas_dimensions,
                    creator=creator,
                    anno_type="Events",
                    page_type=uf.AnnotationPageType.EVENTS
                )
        else:
            normalized_page_text = ""  # TODO: generate

        annotation_page_builder.normalized_page_text = normalized_page_text
        self.transcription_annotation_page = annotation_page_builder.build()

    @staticmethod
    def _page_id(canvas_item: dict[str, Any]) -> str:
        return canvas_item["label"]["en"][0].split(" ")[0]

    @staticmethod
    def _as_item(a: dict[str, object]) -> dict[str, object]:
        a.pop("@context", None)
        a.pop("created_by", None)
        return a

    def _make_annotation_page(
            self,
            page_id: str,
            annotations: list[dict[str, object]],
            canvas_dimensions: dict[str, Dimensions],
            creator: dict[str, str],
            anno_type: str,
            page_type: uf.AnnotationPageType
    ):
        context = ["http://iiif.io/api/presentation/3/context.json"]
        # assumption: all annotations have the same @context
        context += annotations[0]["@context"]
        items = [self._as_item(a) for a in annotations]
        dim = canvas_dimensions[page_id]
        page = {
            "@context": context,
            "type": ["DigitalObject", "AnnotationPage"],
            "id": uf.annotation_page_url(page_type, page_id),
            "label": f"{anno_type} of {page_id}.jpg",
            "created_by": creator,
            "partOf": {
                "id": uf.canvas_url(page_id),
                "type": "Canvas",
                "width": dim.width,
                "height": dim.height
            },
            "items": items
        }
        return page

    @staticmethod
    def _read_page_xml(pagexml_path: Path) -> str:
        try:
            log_reading_file(pagexml_path)
            with open(pagexml_path, "r", encoding="utf-8") as f:
                xml_string = f.read()
        except FileNotFoundError:
            logger.error(f"Input file not found: {pagexml_path}")
            sys.exit(1)
        return xml_string
