#!/usr/bin/env python3
import argparse
import json
import os
from argparse import Namespace
from itertools import groupby
from pathlib import Path

from loguru import logger

import globalise_tools.git_tools as git
from globalise_tools.creator import CreatorFactory
from scripts.gt_ner_xmi_to_wa import THIS_SCRIPT_PATH as XMI_TO_WA_SCRIPT_PATH

THIS_SCRIPT_PATH = "scripts/" + os.path.basename(__file__)


def get_arguments() -> Namespace:
    parser = argparse.ArgumentParser(
        description="Group web-annotations to an AnnotationPage, per page",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("annotations",
                        help="The file containing the annotations",
                        type=str
                        )
    return parser.parse_args()


def as_item(a: dict[str, object]) -> dict[str, object]:
    a.pop("@context", None)
    a.pop("created_by", None)
    return a


def write_annotation_page(out_dir: str, pageid: str, page_annotations: list[dict[str, object]],
                          canvas_dimensions: list[list[str]], creator: dict[str, str]):
    inv_nr = pageid.split("_")[-2]
    page_no = int(pageid.split("_")[-1])
    context = ["http://iiif.io/api/presentation/3/context.json"]
    annotation_context = page_annotations[0]["@context"]  # assumption: all annotations have the same @context
    context += annotation_context
    items = [as_item(a) for a in page_annotations]
    width, height = canvas_dimensions[page_no - 1]
    page = {
        "@context": context,
        "type": ["DigitalObject", "AnnotationPage"],
        "id": f"https://globalise-huygens.github.io/document-view-sandbox/iiif/annotations/entities/{pageid}.json",
        "label": f"Entities of {pageid}.jpg",
        "created_by": creator,
        "partOf": {
            "id": f"https://data.globalise.huygens.knaw.nl/manifests/inventories/{inv_nr}.json/canvas/p{page_no}",
            "type": "Canvas",
            "width": width,
            "height": height
        },
        "items": items
    }
    out_path = f"{out_dir}/{pageid}.json"
    logger.info(f"=> {out_path}")
    with open(out_path, "w") as f:
        json.dump(page, f, indent=2, ensure_ascii=False)


def page_id(annotation: dict[str, object]) -> str:
    # ic(annotation)
    target_id = annotation["target"][0]["source"]["id"]
    return target_id.replace("https://data.globalise.huygens.knaw.nl/hdl:20.500.14722/annotations:transcriptions:",
                             "").replace("#page-normalized", "")


def load_manifest(inv_nr: str) -> dict[str, object]:
    manifest_path = f"/Users/bram/workspaces/globalise/manifests/inventories/{inv_nr}.json"
    logger.info(f"<= {manifest_path}")
    with open(manifest_path) as f:
        manifest = json.load(f)
    return manifest


def group_to_page(annotations_path: str) -> None:
    logger.info(f"<= {annotations_path}")
    out_dir = "/".join(annotations_path.split("/")[:-1]) + "/entities"
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    inv_nr = annotations_path.split("/")[1]
    manifest = load_manifest(inv_nr)
    canvas_dimensions = [[c["width"], c["height"]] for c in manifest["items"]]

    with open(annotations_path) as f:
        annotations = json.load(f)

    groups = groupby(annotations, lambda x: page_id(x))
    commit_id = git.read_current_commit_id(warn_on_uncommitted_changes=True)
    cf = CreatorFactory(script_paths=[XMI_TO_WA_SCRIPT_PATH, THIS_SCRIPT_PATH], commit_id=commit_id)
    creator = cf.creator(
        label="Creation of Web Annotations from NER output in XMI format (generated by the GLOBALISE NER model).")
    for pgid, page_annotations in groups:
        write_annotation_page(out_dir, pgid, [pa for pa in page_annotations], canvas_dimensions, creator)


@logger.catch
def main() -> None:
    args = get_arguments()
    group_to_page(args.annotations)


if __name__ == '__main__':
    main()
