#!/usr/bin/env python3
import argparse
import json
import os
import sys
from argparse import Namespace
from itertools import groupby
from pathlib import Path
from typing import Optional

import globalise_tools.git_tools as git
import globalise_tools.url_factory as uf
from globalise_tools.creator import CreatorFactory
from loguru import logger
from scripts.gt_ner_xmi_to_wa import THIS_SCRIPT_PATH as XMI_TO_WA_SCRIPT_PATH

THIS_SCRIPT_PATH = "scripts/" + os.path.basename(__file__)


def get_arguments() -> Namespace:
    parser = argparse.ArgumentParser(
        description="Group web-annotations to an AnnotationPage, per page",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("-v",
                        help="Turn on logging",
                        action="store_true",
                        default=False,
                        dest='verbose'
                        )
    parser.add_argument("-m",
                        "--manifests-dir",
                        help="The directory containing the manifest files, one per inventory number",
                        type=str,
                        required=True
                        )
    parser.add_argument("--git-commit",
                        help="The git commit to use for the provenance (will be calculated if omitted)",
                        type=str
                        )
    parser.add_argument("annotations",
                        help="The file containing the annotations",
                        type=str
                        )
    return parser.parse_args()


def as_item(a: dict[str, object]) -> dict[str, object]:
    a.pop("@context", None)
    a.pop("created_by", None)
    return a


def write_annotation_page(
        out_dir: str,
        pageid: str,
        page_annotations: list[dict[str, object]],
        canvas_dimensions: list[list[str]],
        creator: dict[str, str]
):
    inv_nr = pageid.split("_")[-2]
    page_no = int(pageid.split("_")[-1])
    context = ["http://iiif.io/api/presentation/3/context.json"]
    annotation_context = page_annotations[0]["@context"]  # assumption: all annotations have the same @context
    context += annotation_context
    items = [as_item(a) for a in page_annotations]
    width, height = canvas_dimensions[page_no - 1]
    page = {
        "@context": context,
        "type": ["DigitalObject", "AnnotationPage"],
        # "id": f"https://globalise-huygens.github.io/document-view-sandbox/iiif/annotations/entities/{pageid}.json",
        "id": uf.annotation_page_url(uf.AnnotationPageType.ENTITIES, pageid),
        "label": f"Entities of {pageid}.jpg",
        "created_by": creator,
        "partOf": {
            "id": uf.canvas_url(pageid),
            "type": "Canvas",
            "width": width,
            "height": height
        },
        "items": items
    }
    out_path = f"{out_dir}/{pageid}.json"
    logger.info(f"=> {out_path}")
    with open(out_path, "w") as f:
        json.dump(page, f, ensure_ascii=False)


def page_id(annotation: dict[str, object]) -> str:
    # ic(annotation)
    target_id = annotation["target"][0]["source"]["id"]
    return target_id.replace(f"{uf.URI_BASE_PATTERN}annotations:transcriptions:",
                             "").replace("#page-normalized", "")


def load_manifest(manifests_dir: str, inv_nr: str) -> dict[str, object]:
    manifest_path = f"{manifests_dir}/{inv_nr}.json"
    logger.info(f"<= {manifest_path}")
    with open(manifest_path) as f:
        manifest = json.load(f)
    return manifest


def group_to_page(annotations_path: str, manifests_dir: str, git_commit: Optional[str] = None) -> None:
    logger.info(f"<= {annotations_path}")
    out_dir = "/".join(annotations_path.split("/")[:-1]) + "/entities"
    Path(out_dir).mkdir(parents=True, exist_ok=True)
    inv_nr = annotations_path.split("/")[1]
    manifest = load_manifest(manifests_dir, inv_nr)
    canvas_dimensions = [[c["width"], c["height"]] for c in manifest["items"]]

    with open(annotations_path) as f:
        annotations = json.load(f)

    groups = groupby(annotations, lambda x: page_id(x))
    if git_commit:
        commit_id = git_commit
    else:
        commit_id = git.read_current_commit_id(warn_on_uncommitted_changes=True)
    cf = CreatorFactory(script_paths=[XMI_TO_WA_SCRIPT_PATH, THIS_SCRIPT_PATH], commit_id=commit_id)
    creator = cf.creator(
        label="Creation of Web Annotations from NER output in XMI format (generated by the GLOBALISE NER model).")
    for pgid, page_annotations in groups:
        write_annotation_page(out_dir, pgid, [pa for pa in page_annotations], canvas_dimensions, creator)


@logger.catch
def main() -> None:
    args = get_arguments()
    if not args.verbose:
        logger.remove()
        logger.add(sink=sys.stderr, level="WARNING")
    group_to_page(args.annotations, args.manifests_dir, args.git_commit)


if __name__ == '__main__':
    main()
